### ISSUE TITLE
Need to break Packet out of the decoder to make code more readable

### ISSUE THREAD

**Issue by tdunning** [mapr-demos/drill-pcap-format#11]

**Comment by dmitriyHavrilovich** [comment]
I'm working on it already

**Comment by dmitriyHavrilovich** [comment]
I'm thinking of refactor it to get input stream and return stream of parsed DTOs, that fit DrillTable.

**Comment by tdunning** [comment]
DTO's are a disaster for speed. Can't have the allocation and copy costs
and still be fast.

I have already factored Packet to be a static class. Will push to a branch
shortly.

**Comment by Vlad-Storona** [comment]
Commits associated with this problem:

8f029cc2e346366dbbbde5d06bd267426ce9063c
b723ebefb71035091ac9d78a22f2a44b096d63f0
ab4ea326df022b160b9a267624c4c8202db76e66
4cae430319b9364b6f152f167a6f9d0079f57683

**Comment by dmitriyHavrilovich** [comment]
Still need to fix tests
