### ISSUE TITLE
Add IP-Geolocation

### ISSUE THREAD

**Issue by cgivre** [mapr-demos/drill-pcap-format#15]
I also have this UDF which is a wrapper for the MaxMind GeoIP databases (http://dev.maxmind.com/geoip/legacy/geolite/).  I'm happy to contribute them to this, however before I do that I need some assistance with something.  

These functions depend on the binary database file.  Right now, the path is hardcoded in the UDF.  Forgive my ignorance here (`me != java dev`) but what would be the best way to include the file and some sort of relative path to that file?

https://github.com/cgivre/drill-geoip-functions

**Comment by tdunning** [comment]
Charles,

Isn't this best kept as a UDF?

**Comment by cgivre** [comment]
Hi Ted,
Sorry, I wasn't clear.  I had the set of UDFs that I'd like to submit (as
UDFs) to the final PCAP package if there's interest.  I'd like to keep them
as functions, as it would hurt performance to geo-locate every IP.
-- C

**Comment by tdunning** [comment]
Let's get them in separately. Their utility isn't bound together with the
PCAP stuff.



On Thu, Apr 27, 2017 at 10:07 AM, Charles S. Givre <notifications@github.com

**Comment by dmitriyHavrilovich** [comment]
out of the scope of this project.
