### ISSUE TITLE
Add HTTP protocol support

### ISSUE THREAD

**Issue by dmitriyHavrilovich** [mapr-demos/drill-pcap-format#16]

**Comment by Vlad-Storona** [comment]
This file 
https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=6to4.pcap

in Wireshark  looks like this:

![selection_062](https://cloud.githubusercontent.com/assets/13219901/25444833/07133484-2a9c-11e7-967a-2c977a950d32.png)

and in Drill, we have the same output now

![selection_061](https://cloud.githubusercontent.com/assets/13219901/25444836/0a057c06-2a9c-11e7-98f2-3411c86f1020.png)

**Comment by cgivre** [comment]
Hi Vlad,
Is it possible to replicate the info column from Wireshark?  That would be
extremely useful if possible.

**Comment by cgivre** [comment]
One other thought... the Drill plugin doesn't specify the protocol.  I
think I have some code to do that which I can add in the next few days.
-- C

**Comment by Vlad-Storona** [comment]
Hi, Do you mean column names and its order?

**Comment by Vlad-Storona** [comment]
I think it will be great.

**Comment by tdunning** [comment]
Charles,

I would like to get this back into Drill pretty much as it stands. Protocol
decoders can be added at a UDF layer.

For instance, if we had an list aggregator that collected packets from a
session, it would be pretty easy to implement an HTTP decoder that
translates this sequence into a structure with headers, request and so on.
