### ISSUE TITLE
ArrayIndexOutOfBoundsException : on some query

### ISSUE THREAD

**Issue by tgrall** [mapr-demos/drill-pcap-format#3]
Using
the https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=airtunes-1.pcap

Query:
```
select *
from dfs.`data`.`airtunes.pcap`
limit 165
```
raise the following exception:
```
org.apache.drill.common.exceptions.UserRemoteException: SYSTEM ERROR: ArrayIndexOutOfBoundsException: -153020451 Fragment 0:0 [Error Id: 0a2e36a4-de6e-4b90-8bdd-ebd6581ebdd0 on tgrall-mbp.lan:31010]
```

Note that when it is limit 164 it is working, so related to the line 165 (did not take the time to debug)

**Comment by Vlad-Storona** [comment]
The problem was with reading data from a file. When the first buffer was ended, the next chunk of data was improperly copied to a buffer.
