### ISSUE TITLE
Networking Functions

### ISSUE THREAD

**Issue by cgivre** [mapr-demos/drill-pcap-format#6]
Would you be interested in including these networking UDFs in the final PR to Drill?

https://github.com/cgivre/drill-network-functions

I also have a UDF which is a wrapper for the MaxMind GeoIP Database which I can put up on github.

**Comment by kingmesal** [comment]
That would be tremendously useful. Thanks Charles!

________________________________

**Comment by cgivre** [comment]
Created PR #14 
Closing issue.
